#values.yaml
replicaCount: 2

image:
  repository: jobapp-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

mysql:
  enabled: true
  rootPassword: e12345678E
  database: jobapp_db
  user: root

ingress:
  enabled: false
  host: jobapp.local

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi