#backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: jobapp-backend
spec:
  selector:
    app: jobapp-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP