apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jobapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: jobapp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jobapp-backend
                port:
                  number: 8080