#secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jobapp-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: cm9vdA==            # root
  SPRING_DATASOURCE_PASSWORD: ZTEyMzQ1Njc4RQA=    # e12345678E (base64)