apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jobapp.fullname" . }}-secrets
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.mysql.user | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.rootPassword | b64enc }}